--TABLE ROLES
CREATE TABLE ROLES(
    ID_ROL NUMBER,
    PRIVILEGIO NVARCHAR2(50),
    CONSTRAINT ROLES_FK PRIMARY KEY(ID_ROL)
);
DROP TABLE ROLES;

SELECT * FROM ROLES;
INSERT INTO ROLES VALUES(1,'PUBLICO');
INSERT INTO ROLES VALUES(2,'PRIVADO');
INSERT INTO ROLES VALUES(3,'PUBLICO');
INSERT INTO ROLES VALUES(4,'PUBLICO');
INSERT INTO ROLES VALUES(5,'PRIVADO');

CREATE TABLE USUARIO(
    ID_USUARIO NUMBER, 
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(50),
    APM NVARCHAR2(50),
    SEXO NVARCHAR2(25),
    CORREO NVARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    FECHA_CREACION DATE,
    ROL_ID NUMBER,
    CONSTRAINT USUARIO_PK PRIMARY KEY(ID_USUARIO),
    CONSTRAINT ROL_FK FOREIGN KEY (ROL_ID) REFERENCES ROLES(ID_ROL)
);
DROP TABLE USUAARIO;


CREATE OR REPLACE TRIGGER TRG_FECHA_CREACION
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSDATE;
END;
/


INSERT INTO USUARIO (
  ID_USUARIO, NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID) VALUES 
  (1, 'RAUL', 'PEREZ', 'JUAREZ', 'M', 'RAUL.PEREZ@ENUCOM.COM.MX', TO_DATE('1990-05-10', 'YYYY-MM-DD'), 1);

INSERT INTO USUARIO (
  ID_USUARIO, NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID) VALUES 
  (2, 'DANIEL', 'RAMIREZ', 'JIMENEZ', 'M', 'DANIEL.RAMIREZ@ENUCOM.COM.MX', TO_DATE('2001-03-16', 'YYYY-MM-DD'), 3);

INSERT INTO USUARIO (
  ID_USUARIO, NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID) VALUES 
  (3, 'MARITZA', 'LORENZO', 'JIMENEZ', 'F', 'MARITZA.LORENZO@ENUCOM.COM.MX', TO_DATE('1992-12-25', 'YYYY-MM-DD'), 2);

INSERT INTO USUARIO (
  ID_USUARIO, NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID) VALUES 
  (4, 'PAULINA', 'GARCIA', 'RAMIREZ', 'F', 'PAULINA.GARCIA@ENUCOM.COM.MX', TO_DATE('1979-11-10', 'YYYY-MM-DD'), 5);

INSERT INTO USUARIO (
  ID_USUARIO, NOMBRE, APP, APM, SEXO, CORREO, FECHA_NACIMIENTO, ROL_ID) VALUES 
  (5, 'ABRAHAM', 'GARCIA', 'ARIAS', 'M', 'ABRAHAM.GARCIA@ENUCOM.COM.MX', TO_DATE('2005-05-13', 'YYYY-MM-DD'), 3);


DELETE FROM USUARIO WHERE ID_USUARIO=3;
SELECT * FROM USUARIO;

COMMIT;
